import { Geist, Geist_Mono } from "next/font/google";
import { Nunito_Sans } from "next/font/google";

import "@/styles/bootstrap.css";
import "@/styles/globals.css";
import "@/styles/slick-slider/slick/slick.css";
import "@/styles/slick-slider/slick/slick-theme.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import FooterBottom from "@/components/footerBottom/footerBottom";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Takmeel",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (

    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${nunitoSans.variable}`}>
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
        <FooterBottom/>
      </body>
    </html>
  );
}
